import type { AssessmentResult } from '../api/types';
import { formatINR, formatRange } from './formatCurrency';

export const exportPDF = async (data: AssessmentResult): Promise<void> => {
  // Dynamic import to avoid bundle bloat
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

  const W = 210;
  const margin = 20;
  let y = 20;

  const line = () => { doc.setDrawColor(228, 226, 221); doc.line(margin, y, W - margin, y); y += 6; };
  const h1 = (text: string) => { doc.setFont('helvetica', 'bold'); doc.setFontSize(18); doc.setTextColor(13, 13, 13); doc.text(text, margin, y); y += 8; };
  const h2 = (text: string) => { doc.setFont('helvetica', 'bold'); doc.setFontSize(12); doc.setTextColor(13, 13, 13); doc.text(text, margin, y); y += 6; };
  const body = (text: string, indent = 0) => { doc.setFont('helvetica', 'normal'); doc.setFontSize(10); doc.setTextColor(61, 61, 61); doc.text(text, margin + indent, y); y += 5; };
  const kv = (k: string, v: string) => { doc.setFont('helvetica', 'bold'); doc.setFontSize(10); doc.setTextColor(122, 118, 112); doc.text(k, margin, y); doc.setFont('helvetica', 'normal'); doc.setTextColor(13, 13, 13); doc.text(v, margin + 60, y); y += 5; };

  // Header
  doc.setFillColor(255, 107, 53);
  doc.rect(0, 0, W, 14, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(255, 255, 255);
  doc.text('KiranaIQ — Credit Assessment Memo', margin, 9);
  y = 22;

  h1('Assessment Report');
  body(`Generated: ${new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' })}`);
  if (data.store_address) body(`Location: ${data.store_address}`);
  body(`Assessment ID: ${data.assessment_id}`);
  y += 3;
  line();

  h2('Cash Flow Estimates');
  if (data.daily_sales_range) kv('Daily Sales Range', formatRange(data.daily_sales_range));
  if (data.monthly_revenue_range) kv('Monthly Revenue Range', formatRange(data.monthly_revenue_range));
  if (data.monthly_income_range) kv('Monthly Net Income Range', formatRange(data.monthly_income_range));
  if (data.confidence_score) kv('Confidence Score', `${Math.round(data.confidence_score * 100)}%`);
  if (data.recommendation) kv('Recommendation', data.recommendation.replace(/_/g, ' ').toUpperCase());
  y += 3;
  line();

  h2('Key Signals');
  if (data.shelf_density_index) kv('Shelf Density Index', `${Math.round(data.shelf_density_index * 100)}%`);
  if (data.geo_footfall_score) kv('Geo Footfall Score', `${data.geo_footfall_score}/100`);
  if (data.competition_index) kv('Competition Index', `${Math.round(data.competition_index * 100)}%`);
  if (data.sku_diversity_score) kv('SKU Diversity Score', `${data.sku_diversity_score}/10`);
  y += 3;
  line();

  if (data.loan_suggestion) {
    h2('Loan Recommendation');
    kv('Suggested Amount', `${formatINR(data.loan_suggestion.min_loan)} – ${formatINR(data.loan_suggestion.max_loan)}`);
    kv('Tenure', `${data.loan_suggestion.suggested_tenure_months} months`);
    kv('Monthly EMI Range', formatRange(data.loan_suggestion.monthly_emi_range));
    kv('FOIR', `${data.loan_suggestion.foir_used * 100}%`);
    kv('Interest Rate', `${data.loan_suggestion.interest_rate_pa * 100}% p.a.`);
    y += 3;
    line();
  }

  if (data.risk_flags?.length > 0) {
    h2('Risk Flags');
    data.risk_flags.forEach(flag => {
      body(`• [${flag.severity.toUpperCase()}] ${flag.code.replace(/_/g, ' ')}`, 2);
      body(`  ${flag.description}`, 4);
    });
    y += 3;
    line();
  }

  // Footer
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(122, 118, 112);
  doc.text('This report is generated by KiranaIQ AI and is for informational purposes only.', margin, 285);
  doc.text('Lenders should conduct due diligence before credit decisions.', margin, 289);

  doc.save(`KiranaIQ_Assessment_${data.assessment_id.slice(0, 8)}.pdf`);
};